output_dir: .

clear_top_level: true
logical_grouping: true

collections:
  - common
  - typescript

loader_paths:
  - docs

render_context:
  project:
    project_name: env-git
    version: 0.1.0

    verbose_name: Env git
    description: Get git info at runtime.

    repository: https://github.com/JoelLefkowitz/env-git
    codacy_id: e278e54acce54847879f4adeda5627aa

    inserts:
      - usage.md

  author:
    author: Joel Lefkowitz
    author_email: joellefkowitz@hotmail.com
    author_github_handle: joellefkowitz

  package:
    is_npm_package: true
    package_name: env-git

  portfolio:
    is_portfolio: true
    status_level: 2

    languages:
      - TypeScript

    paradigms:
      - Object oriented programming
